### ISSUE TITLE
Travis Build Failed ??

### ISSUE THREAD

**Issue by gnoesnooj** [class071/gaboja#10]
![image](https://user-images.githubusercontent.com/91658692/181431774-c08923dd-3523-433d-a86c-da13b6a73ca3.png)

#9 에 있길래 물어봅니당

이건 어떤건가요 ?

**Comment by gnoesnooj** [comment]
#12  에 또 발생했습니다
기존 #9  에 있던 건 해결된 거 같아 보이는데
어케 해결하신건가용
@we4sley

**Comment by we4sley** [comment]
> #12 에 또 발생했습니다 기존 #9 에 있던 건 해결된 거 같아 보이는데 어케 해결하신건가용 @we4sley

테스트코드 분리가 제대로 되지 않은 것 같아 이 부분 수정하도록 하겠습니다.
